service: accessor-express
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  get-data:
    handler: dist/index.handler
    timeout: 120
    events:
      - httpApi: '*'
    
    

plugins:
  - serverless-offline


custom:
  serverless-offline:
    httpPort: 3001
  